public class Datatype{
     public static void main(String[]args){
     byte alaphebets=26;
     byte months=12;
     byte teeth=32;
     byte planets=8;
     byte weeks=7;
     byte age=22;
     byte BP=86;
     byte temperature=27;
     byte second=60;
     byte keyboardkeys=105;
     short bones=206;
     short costwashingmachine=30000;
     short costofwatch=5000;
     short costofmixer=2000;
     short costofironbox=2500;
     short costofbag=3000;
     short currentbill=2000;
     short refrigerator=30000;
     short laptop=25000;
     short steelbotel=2000;
     int car=50000;
     int sallry=50000;
     int investment=100000;
     int debt=70000;
     int depth=55000;
     int distance=50000;
     int mobilephone=100000;
     int rentofhouse=50000;
     int gold=65000;
     int waterquantity=70000;  
     long networth=100000000l;
     long adhar=302015256828l;
     long phonenumber=9036922415l;
     long rbc=5700000000l;
     long likes=20000000l;
     long subscriber=100000000l;
     long girlspopulation=660000000000l;
     long gt650=400000l;
     long boyspopulation=710000000000l;
     long hiendgamingpc=500000l;
     float rbcm1=4.7f;
     float rbcf2=4.2f;
     float pie3=3.14f;
     float population4=1.4f;
     float cgpa5=8.49f;
     float datagb6=2.5f;
     float height7=4.5f;
     float kilometer8=3.5f;
     float percentage9=85.6f;
     float litre11=5.6f;
     double rbcm=4.7d;
     double rbcf=4.2d;
     double pie=3.14d;
     double population=1.4d;
     double cgpa=8.49d;
     double datagb=2.5d;
     double height=4.5d;
     double kilometer=3.5d;
     double percentage=85.6d;
     double litre=5.6d;
     boolean iscoming=true;
     boolean twoisgreaterthenone=true;
     boolean oneissmallerthentwo=false;
     boolean isgoing=false;
     boolean isstanding=true;
     boolean isswimming=false;
     boolean isdancing=false;
     boolean issitting=true;
     boolean drinkingtea=false;
     boolean isbringpen=true;
     char ch1='m';
     char ch2='f';
     char ch3='a';
     char ch4='b';
     char ch5='c';
     char ch6='d';
     char ch7='f';
     char ch8='g'; 
     char ch9='h';
     char ch10='i';
     System.out.println(alaphebets);
     System.out.println(months);
     System.out.println(teeth);
     System.out.println(planets);
     System.out.println(weeks);
     System.out.println(age);
     System.out.println(percentage);
     System.out.println(temperature);
     System.out.println(second);
     System.out.println(keyboardkeys);
     System.out.println(bones);
     System.out.println(costwashingmachine); 
     System.out.println(costofwatch);
     System.out.println(costofmixer); 
     System.out.println(costofironbox);
     System.out.println(costofbag); 
     System.out.println(currentbill);
     System.out.println(refrigerator);
     System.out.println(laptop); 
     System.out.println(steelbotel);
      System.out.println(car);   
       System.out.println(sallry); 
     System.out.println( investment); 
      System.out.println( debt); 
      System.out.println( depth); 
      System.out.println(distance);  
      System.out.println(mobilephone);  
     System.out.println(rentofhouse);   
      System.out.println( gold); 
      System.out.println( waterquantity); 
      System.out.println(networth);  
       System.out.println( adhar);
      System.out.println( phonenumber); 
      System.out.println(rbc);  
       System.out.println( likes);
      System.out.println(subscriber);  
      System.out.println(girlspopulation);  
      System.out.println(gt650);  
      System.out.println(boyspopulation);  
      System.out.println(hiendgamingpc);  
      System.out.println( rbcm1); 
     System.out.println(rbcf2);  
     System.out.println(pie3);  
     System.out.println( population4); 
      System.out.println(cgpa5); 
      System.out.println(datagb6); 
     System.out.println(height7);  
      System.out.println(kilometer8);  
      System.out.println( percentage9); 
      System.out.println( litre11); 
     System.out.println( rbcm); 
     System.out.println(rbcf);  
     System.out.println(pie);  
     System.out.println( population); 
      System.out.println(cgpa); 
      System.out.println(datagb); 
     System.out.println(height);  
     System.out.println(kilometer);  
     System.out.println(percentage);  
     System.out.println( litre); 
     System.out.println( iscoming);  
     System.out.println( twoisgreaterthenone);  
    System.out.println( oneissmallerthentwo); 
    System.out.println( isgoing);   
     System.out.println(isstanding);  
  System.out.println( isswimming);  
   System.out.println(isdancing);    
    System.out.println(issitting);  
    System.out.println(drinkingtea); 
     System.out.println( isbringpen);
      System.out.println(ch1);  
     System.out.println( ch2);  
     System.out.println(ch3);   
     System.out.println(ch4);   
     System.out.println(ch5);   
     System.out.println(ch6);   
     System.out.println(  ch7); 
     System.out.println(ch8);   
      System.out.println(ch9);  
     System.out.println(ch10);   
     
     
}
}